disabled_rules:
    - cyclomatic_complexity
    - deployment_target
    - file_length
    - function_parameter_count
    - leading_whitespace
    - line_length
    - trailing_whitespace
    - function_body_length
    - identifier_name
    - type_body_length
